# NumPy Basics
*Learning notes for the foundational library of scientific computing.*


## 1. What is ndarray?
The `ndarray` (N-dimensional array) is the core data structure of NumPy.


In [12]:
import  numpy as np

In [238]:
arr=np.array(5) #create a 0 dimension array
print("Array:", arr)
print("Dimensions (ndim):", arr.ndim) #number of dimensions

Array: 5
Dimensions (ndim): 0


In [239]:
arr=np.array([1,2,3]) #create a 1 dimension array
print("Array:", arr)
print("Dimensions (ndim):", arr.ndim)#number of dimensions

Array: [1 2 3]
Dimensions (ndim): 1


In [240]:
arr=np.array([[1,2,3],[4,5,6]]) #create a 2 dimension array
print("Array:", arr)
print("Dimensions (ndim):", arr.ndim)#number of dimensions

Array: [[1 2 3]
 [4 5 6]]
Dimensions (ndim): 2


## 2. Characteristics of ndarray
- **Homogeneity**: All elements must be of the same data type.
- **Fixed size**: Arrays are fixed at creation.

In [241]:
arr=np.array([1,'hello'])
print("Array:", arr)

Array: ['1' 'hello']


In [242]:
arr=np.array([1,2.5])
print("Array:", arr)

Array: [1.  2.5]


## 3. Properties of ndarray
Key attributes include `shape`, `ndim`, `size`, and `dtype`.

In [245]:
arr=np.array(1)
print("Array:", arr)
print("Shape:", arr.shape)
print("Dimensions (ndim):", arr.ndim)
print("Size:", arr.size)
print("DType:", arr.dtype)
print("Transpose:", arr.T)

Array: 1
Shape: ()
Dimensions (ndim): 0
Size: 1
DType: int64
Transpose: 1


In [246]:
arr=np.array([1,2,3])
print("Array:", arr)
print("Shape:", arr.shape)
print("Dimensions (ndim):", arr.ndim)
print("Size:", arr.size)
print("DType:", arr.dtype)
print("Transpose:", arr.T)

Array: [1 2 3]
Shape: (3,)
Dimensions (ndim): 1
Size: 3
DType: int64
Transpose: [1 2 3]


In [248]:
print(arr.shape)
arr = np.array([[1, 2, 3],[4,5,6]])
print("Array:", arr)
print("Shape:", arr.shape)
print("Dimensions (ndim):", arr.ndim)
print("Size:", arr.size)
print("DType:", arr.dtype)
print("Transpose:\n", arr.T)

(2, 3)
Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions (ndim): 2
Size: 6
DType: int64
Transpose:
 [[1 4]
 [2 5]
 [3 6]]


## 4. Ways to Create Arrays
NumPy provides various methods to initialize arrays, such as `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`, and more.

In [250]:
list1=[2,3,4]
arr=np.array(list1,dtype=float)
print("Dimensions (ndim):", arr.ndim)
print("Array:", arr)

Dimensions (ndim): 1
Array: [2. 3. 4.]


In [251]:
#copy
arr1=np.copy(arr)
print("Array1:", arr1)

Array1: [2. 3. 4.]


In [252]:
arr1[0]=8
print("Array1:", arr1)
print("Array:", arr)

Array1: [8. 3. 4.]
Array: [2. 3. 4.]


In [253]:
arr=np.zeros((2,3))
print("Array:", arr)
print("DType:", arr.dtype)

Array: [[0. 0. 0.]
 [0. 0. 0.]]
DType: float64


In [257]:
arr=np.ones((2,3))
print("Array:\n", arr)
print("DType:", arr.dtype)

Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
DType: float64


In [256]:
arr=np.empty((2,2))
print("Array:\n", arr)

Array:
 [[1.e-323 1.e-323]
 [1.e-323 5.e-324]]


In [50]:
arr=np.full((2,2),2026)
print(arr)

[[2026 2026]
 [2026 2026]]


In [258]:
arr2=np.zeros_like(arr1)
print("Array2:\n", arr2)
arr2=np.empty_like(arr1)
print("Array2:\n", arr2)
arr2=np.ones_like(arr1)
print("Array2:\n", arr2)
arr2=np.full_like(arr1,200)
print("Array2:\n", arr2)

Array2:
 [0. 0. 0.]
Array2:
 [0. 0. 0.]
Array2:
 [1. 1. 1.]
Array2:
 [200. 200. 200.]


In [259]:
arr=np.arange(1,10,1)  #start,end,step
print("Array:\n", arr)

Array:
 [1 2 3 4 5 6 7 8 9]


In [260]:
arr=np.linspace(1,10,5)
print("Array:\n", arr)

Array:
 [ 1.    3.25  5.5   7.75 10.  ]


In [261]:
arr=np.linspace(0,100,5,dtype=int)
print("Array:\n", arr)
arr=np.arange(0,101,25)
print("Array:\n", arr)

Array:
 [  0  25  50  75 100]
Array:
 [  0  25  50  75 100]


In [262]:
arr=np.logspace(0,4,3,base=2)
print("Array:\n", arr)

Array:
 [ 1.  4. 16.]


In [263]:
arr=np.eye(3,4,dtype=int)
print("Array:\n", arr)

Array:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [264]:
arr=np.diag([5,1,2,3])
print("Array:\n", arr)

Array:
 [[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [265]:
arr=np.random.rand(2,3)
print("Array:\n", arr)

Array:
 [[0.77815675 0.87001215 0.97861834]
 [0.79915856 0.46147936 0.78052918]]


In [266]:
arr=np.random.uniform(3,6,(2,3))
print("Array:\n", arr)

Array:
 [[3.35482328 4.91976306 3.43005986]
 [5.83400675 4.56554497 4.24398582]]


In [267]:
arr=np.random.randint(3,30,(2,3))
print("Array:\n", arr)

Array:
 [[ 6 14 21]
 [26  5  3]]


In [268]:
arr=np.random.randn(2,3)
print("Array:\n", arr)

Array:
 [[ 0.04575852 -0.18718385  1.53277921]
 [ 1.46935877  0.15494743  0.37816252]]


In [72]:
np.random.seed(20)
arr=np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


In [269]:
arr=np.array([1,0,1,0],dtype=bool)
print("Array:\n", arr)

Array:
 [ True False  True False]


## 5.1 Indexing & Slicing
Accessing and modifying array elements using indices, slices, and boolean masks.

In [270]:
arr=np.random.randint(1,100,20)
print("Array:\n", arr)

Array:
 [59 32  2 66 42 58 36 12 47 83 92  1 15 54 13 43 85 76 69  7]


In [271]:
# 1. Single element access
print("arr[0] (First element):", arr[0])
# 2. Full slice
print("arr[:] (Full array):", arr[:])
# 3. Slice from index 2 to 5
print("arr[2:5]:", arr[2:5])
# 4. Slice using `slice()` object (functionally identical to [2:5])
print("arr[slice(2,5)]:", arr[slice(2,5)])
# 5. Slice with step size (from index 2 to 5, step 2)
print("arr[slice(2,5,2)]:", arr[slice(2,5,2)])
# 6. Boolean masking: Select all elements greater than 10
print("arr[arr>10] (Elements > 10):", arr[arr>10])
# 7. Boolean masking: Select elements between 10 and 30
print("arr[(arr>10) & (arr<30)] (10 < elements < 30):", arr[(arr>10) & (arr<30)])

arr[0] (First element): 59
arr[:] (Full array): [59 32  2 66 42 58 36 12 47 83 92  1 15 54 13 43 85 76 69  7]
arr[2:5]: [ 2 66 42]
arr[slice(2,5)]: [ 2 66 42]
arr[slice(2,5,2)]: [ 2 42]
arr[arr>10] (Elements > 10): [59 32 66 42 58 36 12 47 83 92 15 54 13 43 85 76 69]
arr[(arr>10) & (arr<30)] (10 < elements < 30): [12 15 13]


In [272]:
arr=np.random.randint(1,100,(4,8))
print("Array:\n", arr)

Array:
 [[69 48  4 77 53 79 16 21]
 [59 24 80 14 86 49 50 70]
 [42 36 65 96 70 95  1 51]
 [37 35 49 94  4 99 43 78]]


In [275]:
# 1. Accessing an element in a 2D array (row, column)
print("arr[1,3] (Element at row 1, column 3):", arr[1,3])
# 2. Slicing a row (Row 1, Columns 2 to 4)
print("arr[1, 2:5] (Row 1, columns 2 to 4):", arr[1, 2:5])
# 3. Boolean masking on the entire 2D array
# This flattens the result into a 1D array with all elements > 40
print("arr[arr>40] (Flattened elements > 40):", arr[arr>40])
# 4. Composed indexing: Access row 2 first, then mask inside it
print("arr[2][arr[2]>50] (Row 2 elements > 50):", arr[2][arr[2]>50])

arr[1,3] (Element at row 1, column 3): 14
arr[1, 2:5] (Row 1, columns 2 to 4): [80 14 86]
arr[arr>40] (Flattened elements > 40): [69 48 77 53 79 59 80 86 49 50 70 42 65 96 70 95 51 49 94 99 43 78]
arr[2][arr[2]>50] (Row 2 elements > 50): [65 96 70 95 51]


### 5.2 Understanding NumPy Broadcasting

Broadcasting is NumPy's powerful feature that allows arithmetic operations between arrays of different shapes.

- **Scalar Broadcasting**: A single number (scalar) is applied to every element in an array.
- **General Broadcasting**: When an array has a dimension of `1`, NumPy stretches it to match the other array's dimension (e.g., `(3,)` + `(3,1)` generates a `(3,3)` matrix).

In [276]:
a= np.array([1,2,3])
b= np.array([4,5,6])
print("a + b (addition):", a + b)
print("a - b (subtraction):", a - b)
print("a * b (multiplication):", a * b)
print("a / b (division):", a / b)

a + b (addition): [5 7 9]
a - b (subtraction): [-3 -3 -3]
a * b (multiplication): [ 4 10 18]
a / b (division): [0.25 0.4  0.5 ]


In [277]:
c = [1, 2, 3]
d = [4, 5, 6]
# Python list concatenation
print("Python list c + d (Concatenation):", c + d)
# Python list element-wise addition using a for loop
# Note: The `+` operator on lists doesn't do math, so we need loops
for i in range(len(c)):
    d[i] = d[i] + c[i]
print("Python list after manual for-loop addition:", d)

Python list c + d (Concatenation): [1, 2, 3, 4, 5, 6]
Python list after manual for-loop addition: [5, 7, 9]


In [283]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Original 2D array:")
print(a)
print("-" * 66)
print("a + 3 (Scalar addition broadcast to all elements):\n",a + 3)
print("a * 3 (Scalar multiplication broadcast to all elements):\n",a * 3)

Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------------------------------------------
a + 3 (Scalar addition broadcast to all elements):
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
a * 3 (Scalar multiplication broadcast to all elements):
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [286]:
# Broadcasting subtraction
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])
print("a shape:", a.shape)
print("b shape:", b.shape)
print("-" * 66)
print("a + b (Broadcasting addition):")
print(a + b)
print("\nb - a (Broadcasting subtraction, generates 3x3 matrix):")
print(b - a)

a shape: (3,)
b shape: (3, 1)
------------------------------------------------------------------
a + b (Broadcasting addition):
[[5 6 7]
 [6 7 8]
 [7 8 9]]

b - a (Broadcasting subtraction, generates 3x3 matrix):
[[3 2 1]
 [4 3 2]
 [5 4 3]]


In [287]:
# Matrix multiplication (Dot product)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])

print("Matrix A:\n", a)
print("Matrix B:\n", b)
print("-" * 66)

print("a @ b (Matrix Multiplication / Dot Product):")
print(a @ b)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[4 5 6]
 [7 8 9]
 [1 2 3]]
------------------------------------------------------------------
a @ b (Matrix Multiplication / Dot Product):
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


In [289]:
# --- 1. Square Root and Power ---
print("np.sqrt(9.0):", np.sqrt(9.0))
print("np.sqrt([1, 4, 9]):", np.sqrt([1, 4, 9]))
arr = np.array([1, 25, 81])
print("np.sqrt(array):", np.sqrt(arr))
print("-" * 66)
# --- 2. Exponential and Logarithm ---
print("np.exp(1) (Euler's number e):", np.exp(1))
print("np.log(2.718...):", np.log(2.718281828459045))
print("-" * 66)
# --- 3. Trigonometric Functions (Radians) ---
print("np.sin(-1):", np.sin(-1))
print("np.cos(np.pi):", np.cos(np.pi))
print("-" * 66)
# --- 4. Absolute and Power ---
arr = np.array([-1, 2, 4])
print("np.abs([-1, 2, 4]):", np.abs(arr))
print("np.power([-1, 2, 4], 3):", np.power(arr, 3))

np.sqrt(9.0): 3.0
np.sqrt([1, 4, 9]): [1. 2. 3.]
np.sqrt(array): [1. 5. 9.]
------------------------------------------------------------------
np.exp(1) (Euler's number e): 2.718281828459045
np.log(2.718...): 1.0
------------------------------------------------------------------
np.sin(-1): -0.8414709848078965
np.cos(np.pi): -1.0
------------------------------------------------------------------
np.abs([-1, 2, 4]): [1 2 4]
np.power([-1, 2, 4], 3): [-1  8 64]


In [290]:
# --- Rounding, Ceiling, Floor ---
arr = np.array([3.5, 9.1, 7.6])
print("Original array:", arr)
print("np.round(arr) (Nearest integer):", np.round(arr))
print("np.ceil(arr) (Smallest integer >= element):", np.ceil(arr))
print("np.floor(arr) (Largest integer <= element):", np.floor(arr))
print("-" * 66)

# --- Check for NaN (Not a Number) ---
print("np.isnan([1, 2, 3]):", np.isnan([1, 2, 3]))
print("np.isnan([1, 2, 3, np.nan]):", np.isnan([1, 2, 3, np.nan]))

Original array: [3.5 9.1 7.6]
np.round(arr) (Nearest integer): [4. 9. 8.]
np.ceil(arr) (Smallest integer >= element): [ 4. 10.  8.]
np.floor(arr) (Largest integer <= element): [3. 9. 7.]
------------------------------
np.isnan([1, 2, 3]): [False False False]
np.isnan([1, 2, 3, np.nan]): [False False False  True]


In [291]:
arr = np.random.randint(1, 20, 8)
print("Original array:", arr)
print("-" * 30)

print("Sum (np.sum):", np.sum(arr))
print("Mean (Average, np.mean):", np.mean(arr))
print("Median (np.median):", np.median(arr))
print("Variance (np.var):", np.var(arr))
print("Standard Deviation (np.std):", np.std(arr))
print("Max & Argmax (np.max, np.argmax):", np.max(arr), "(at index", np.argmax(arr), ")")
print("Min & Argmin (np.min, np.argmin):", np.min(arr), "(at index", np.argmin(arr), ")")

Original array: [17  8 10  1 11 19 12  3]
------------------------------
Sum (np.sum): 81
Mean (Average, np.mean): 10.125
Median (np.median): 10.5
Variance (np.var): 33.609375
Standard Deviation (np.std): 5.797359312652615
Max & Argmax (np.max, np.argmax): 19 (at index 5 )
Min & Argmin (np.min, np.argmin): 1 (at index 3 )


In [292]:
np.random.seed(0)
arr = np.random.randint(0, 100, 4)
print("Original array:", arr)
print("np.median(arr):", np.median(arr))
print("np.percentile(arr, 50):", np.percentile(arr, 50))
print("np.percentile(arr, 25) (1st Quartile):", np.percentile(arr, 25))

Original array: [44 47 64 67]
np.median(arr): 55.5
np.percentile(arr, 50): 55.5
np.percentile(arr, 25) (1st Quartile): 46.25


In [293]:
# --- Cumulative Sum and Product ---
arr = np.array([1, 2, 3])
print("Original array:", arr)
print("-" * 66)

print("np.cumsum(arr) (Cumulative sum):", np.cumsum(arr))
print("np.cumprod(arr) (Cumulative product):", np.cumprod(arr))

Original array: [1 2 3]
------------------------------------------------------------------
np.cumsum(arr) (Cumulative sum): [1 3 6]
np.cumprod(arr) (Cumulative product): [1 2 6]


In [294]:
# --- Comparison Functions ---
print("np.greater([2,3,4,5,6,7], 4):", np.greater([2,3,4,5,6,7], 4))
print("np.less([2,3,4,5,6,7], 4):", np.less([2,3,4,5,6,7], 4))
print("np.equal([2,3,4,5,6,7], 4):", np.equal([2,3,4,5,6,7], 4))
print("np.equal([3,4,5], [4,4,4]):", np.equal([3,4,5], [4,4,4]))
print("-" * 66)

# --- Logical Operations ---
print("np.logical_and([0, 0], [1, 1]):", np.logical_and([0, 0], [1, 1]))
print("np.logical_or([0, 0], [1, 1]):", np.logical_or([0, 0], [1, 1]))
print("np.logical_not([0, 0]):", np.logical_not([0, 0]))
print("np.any([0, 0, 0, 0, 0]):", np.any([0, 0, 0, 0, 0]))
print("np.all([1, 1, 1, 1, 1]):", np.all([1, 1, 1, 1, 1]))

np.greater([2,3,4,5,6,7], 4): [False False False  True  True  True]
np.less([2,3,4,5,6,7], 4): [ True  True False False False False]
np.equal([2,3,4,5,6,7], 4): [False False  True False False False]
np.equal([3,4,5], [4,4,4]): [False  True False]
------------------------------------------------------------------
np.logical_and([0, 0], [1, 1]): [False False]
np.logical_or([0, 0], [1, 1]): [ True  True]
np.logical_not([0, 0]): [ True  True]
np.any([0, 0, 0, 0, 0]): False
np.all([1, 1, 1, 1, 1]): True


In [295]:
# --- np.where for Conditional Replacement ---
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

# Keep original value if < 3, else replace with 0
print("np.where(arr < 3, arr, 0):", np.where(arr < 3, arr, 0))

# Replace with 1 if < 3, else replace with 0
print("np.where(arr < 3, 1, 0):", np.where(arr < 3, 1, 0))

Original array: [1 2 3 4 5]
np.where(arr < 3, arr, 0): [1 2 0 0 0]
np.where(arr < 3, 1, 0): [1 1 0 0 0]


In [296]:
score = np.random.randint(50, 100, 20)
print("Random Scores:", score)
print("-" * 30)

# Single condition: Pass or Fail
print("Threshold 50 (Pass/Fail):\n", np.where(score < 50, 'fail', 'pass'))

# Nested condition: Fail (<60), Pass (60-80), Good (>80)
print("\nNested Threshold (Fail/Pass/Good):\n", np.where(score < 60, 'fail', np.where(score < 80, 'pass', 'good')))

Random Scores: [53 89 59 69 71 86 73 56 74 74 62 51 88 89 73 96 74 67 87 75]
------------------------------
Threshold 50 (Pass/Fail):
 ['pass' 'pass' 'pass' 'pass' 'pass' 'pass' 'pass' 'pass' 'pass' 'pass'
 'pass' 'pass' 'pass' 'pass' 'pass' 'pass' 'pass' 'pass' 'pass' 'pass']

Nested Threshold (Fail/Pass/Good):
 ['fail' 'good' 'fail' 'pass' 'pass' 'good' 'pass' 'fail' 'pass' 'pass'
 'pass' 'fail' 'good' 'good' 'pass' 'good' 'pass' 'pass' 'good' 'pass']


In [299]:
# --- Sorting, Argsort, and Unique ---
np.random.seed(0)
arr = np.random.randint(0, 100, 20)
print("Original random array:", arr)

print("np.sort(arr) (Sorted ascending):", np.sort(arr))
print("np.argsort(arr) (Indices that would sort the array):\n", np.argsort(arr))
print("np.unique(arr) (Unique sorted values):\n", np.unique(arr))

Original random array: [44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88]
np.sort(arr) (Sorted ascending): [ 9 12 21 36 39 44 46 47 58 64 65 67 67 70 83 87 87 88 88 88]
np.argsort(arr) (Indices that would sort the array):
 [ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6 17  9 11 12 19]
np.unique(arr) (Unique sorted values):
 [ 9 12 21 36 39 44 46 47 58 64 65 67 70 83 87 88]


In [301]:
# --- Concatenating Arrays ---
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("arr1:", arr1)
print("arr2:", arr2)
print("arr1 + arr2 (Element-wise addition, not concatenation):", arr1 + arr2)
print("np.concatenate([arr1, arr2]) (Correct way to join arrays):", np.concatenate([arr1, arr2]))

arr1: [1 2 3]
arr2: [4 5 6]
arr1 + arr2 (Element-wise addition, not concatenation): [5 7 9]
np.concatenate([arr1, arr2]) (Correct way to join arrays): [1 2 3 4 5 6]


In [302]:
print("Original array:", arr)
print("-" * 30)
print("np.split(arr, [6, 12, 18]):\n", np.split(arr, [6, 12, 18]))

Original array: [44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88]
------------------------------
np.split(arr, [6, 12, 18]):
 [array([44, 47, 64, 67, 67,  9], dtype=int32), array([83, 21, 36, 87, 70, 88], dtype=int32), array([88, 12, 58, 65, 39, 87], dtype=int32), array([46, 88], dtype=int32)]


In [303]:
print("Original array (Shape: 20,):", arr)
print("-" * 30)
print("np.reshape(arr, (2, 10)) (Reshaped to 2 rows, 10 cols):\n", np.reshape(arr, (2, 10)))

Original array (Shape: 20,): [44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88]
------------------------------
np.reshape(arr, (2, 10)) (Reshaped to 2 rows, 10 cols):
 [[44 47 64 67 67  9 83 21 36 87]
 [70 88 88 12 58 65 39 87 46 88]]


## 6. Practice Examples

In [304]:
# ------------------- Exercise 1: Temperature Data -------------------
temps = np.array([28, 30, 29, 31, 32, 30, 29])
print("Temperature array:", temps)
print("-" * 30)
print(f"Average temperature: {np.mean(temps):.3f}")
print(f"Max temperature: {np.max(temps)}")
print(f"Min temperature: {np.min(temps)}")
days_over_30 = np.count_nonzero(temps > 30)
print(f"Days with temp > 30: {days_over_30}")

cumsum_count = np.cumsum(np.where(temps > 30, 1, 0))[-1]
print(f"Count using cumsum trick: {cumsum_count}")
print("-" * 40)

# ------------------- Exercise 2: Student Scores -------------------
score = np.array([85, 90, 78, 92, 88])
print("Scores array:", score)
print("Sorted scores:", np.sort(score))
print(f"Average score: {np.mean(score)}")
print(f"Median score: {np.median(score)}")
print(f"Standard deviation (std): {np.std(score):.3f}")
print("Scores divided by 10:", score / 10)

Temperature array: [28 30 29 31 32 30 29]
------------------------------
Average temperature: 29.857
Max temperature: 32
Min temperature: 28
Days with temp > 30: 2
Count using cumsum trick: 2
----------------------------------------
Scores array: [85 90 78 92 88]
Sorted scores: [78 85 88 90 92]
Average score: 86.6
Median score: 88.0
Standard deviation (std): 4.883
Scores divided by 10: [8.5 9.  7.8 9.2 8.8]


In [305]:
# ------------------- Exercise 3: Matrix Operations -------------------
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("-" * 30)
print("A + B (Element-wise Addition):\n", A + B)
print("A * B (Element-wise Multiplication):\n", A * B)
print("A @ B (Matrix Multiplication):\n", A @ B)
print("np.dot(A, B) (Equivalent to @):\n", np.dot(A, B))
print("-" * 40)

# ------------------- Exercise 4: Applying Axis -------------------
np.random.seed(0)
arr = np.random.randint(0, 10, (3, 4))
print("Random 2D array (3x4):\n", arr)
print("-" * 30)
print("Max per column (axis=0):", np.max(arr, axis=0))
print("Min per row (axis=1):", np.min(arr, axis=1))
print("\nReplace odd numbers with -1:\n", np.where(arr % 2 == 1, -1, arr))
print("Extracted odd values:", arr[arr % 2 == 1])

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
------------------------------
A + B (Element-wise Addition):
 [[ 6  8]
 [10 12]]
A * B (Element-wise Multiplication):
 [[ 5 12]
 [21 32]]
A @ B (Matrix Multiplication):
 [[19 22]
 [43 50]]
np.dot(A, B) (Equivalent to @):
 [[19 22]
 [43 50]]
----------------------------------------
Random 2D array (3x4):
 [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
------------------------------
Max per column (axis=0): [7 9 7 6]
Min per row (axis=1): [0 3 2]

Replace odd numbers with -1:
 [[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]
Extracted odd values: [5 3 3 7 9 3 5 7]


In [306]:
# ------------------- Exercise 5: Reshaping and Axis Stats -------------------
arr = np.arange(1, 13)
print("Original 1D array:", arr)
arr_reshaped = np.reshape(arr, (3, 4))
print("Reshaped to (3, 4):\n", arr_reshaped)
print("-" * 30)
print("Sum per row (axis=1):", np.sum(arr_reshaped, axis=1))
print("Mean per column (axis=0):", np.mean(arr_reshaped, axis=0))
print("Flatten back to 1D:", np.reshape(arr_reshaped, (12)))
print("-" * 40)

# ------------------- Exercise 6: 5x5 Masking & Replacement -------------------
np.random.seed(0)
arr = np.random.randint(0, 20, (5, 5))
print("Random 5x5 array:\n", arr)
print("-" * 30)
print("Flat values > 10:", arr[arr > 10])
print("Replace > 10 with 0:\n", np.where(arr > 10, 0, arr))

Original 1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped to (3, 4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
------------------------------
Sum per row (axis=1): [10 26 42]
Mean per column (axis=0): [5. 6. 7. 8.]
Flatten back to 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]
----------------------------------------
Random 5x5 array:
 [[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
------------------------------
Flat values > 10: [12 15 19 18 12 14 17 13 19 16 19]
Replace > 10 with 0:
 [[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [307]:
# ------------------- Exercise 7: Financial Summations -------------------
money = np.array([120, 135, 110, 125, 130, 140])
print("Money array:", money)
print(f"Total sum: {np.sum(money)}")
print(f"Mean: {np.mean(money)}")
print(f"Variance: {np.var(money):.2f}")
# Use +1 because Argmax returns index starting from 0
print(f"Day with max income (index+1): {np.argmax(money) + 1}")
print(f"Day with min income (index+1): {np.argmin(money) + 1}")
print("-" * 40)

# ------------------- Exercise 8: Concatenate & Reshape -------------------
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.concatenate([A, B])
print("Concatenated C:", C)
print("Reshaped C (2, 3):\n", np.reshape(C, (2, 3)))
print("-" * 40)

# ------------------- Exercise 9: Frequency Counting -------------------
arr = np.array([[2, 1, 2, 3, 1, 4, 3]])
u_arr, counts = np.unique(arr, return_counts=True)
print("Unique values:", u_arr)
print("Frequencies:", counts)

# (Optional) Here is the manual for-loop approach to compare:
d = []
for i in range(len(u_arr)):
    d.append(len(arr[arr == u_arr[i]]))
print("Manual frequencies check:", d)
print("-" * 40)

# ------------------- Exercise 10: Expense/Revenue Difference -------------------
money = np.array([20, 25, 22, 30, 28])
a = np.array([15, 18, 16, 22, 20])
diff = money - a
print("Profit/Expense difference array:", diff)
print(f"Mean difference: {np.mean(diff)}")
print(f"Std of diff: {np.std(diff):.3f}")
print(f"Variance of diff: {np.var(diff):.3f}")
max_diff = np.max(diff)
print(f"Max profit: {max_diff}")
print(f"Days with max profit: {len(diff[diff == max_diff])}")

Money array: [120 135 110 125 130 140]
Total sum: 760
Mean: 126.66666666666667
Variance: 97.22
Day with max income (index+1): 6
Day with min income (index+1): 3
----------------------------------------
Concatenated C: [1 2 3 4 5 6]
Reshaped C (2, 3):
 [[1 2 3]
 [4 5 6]]
----------------------------------------
Unique values: [1 2 3 4]
Frequencies: [2 2 2 1]
Manual frequencies check: [2, 2, 2, 1]
----------------------------------------
Profit/Expense difference array: [5 7 6 8 8]
Mean difference: 6.8
Std of diff: 1.166
Variance of diff: 1.360
Max profit: 8
Days with max profit: 2
